apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevOps-CICD-Project-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: DevOps-CICD-Project
  template:
    metadata:
      labels:
        app: DevOps-CICD-Project
    spec:
      containers:
      - name: DevOps-CICD-Project
        image: nisanhe/DevOps-CICD-Project:latest
        ports:
        - containerPort: 80
