apiVersion: v1
kind: Service
metadata:
  name: devops-cicd-project-service
spec:
  type: NodePort
  selector:
    app: devops-cicd-project
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
